# Generated by Copilot
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('vault', '0004_saveevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletentry',
            name='card_type',
            field=models.CharField(blank=True, choices=[('debit', 'Debit Card'), ('credit', 'Credit Card')], max_length=10),
        ),
    ]
