# Generated by Django 5.2.1 on 2025-06-17 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0008_remove_sessionlog_admin_user_applogentry_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemLog',
        ),
    ]
