# Generated by Django 5.2.1 on 2025-06-17 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0009_delete_systemlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('terminate', 'Terminate Session'), ('terminate_all', 'Terminate All Sessions'), ('delete', 'Delete Session'), ('create', 'Create Object'), ('update', 'Update Object'), ('delete_obj', 'Delete Object')], max_length=32)),
                ('object_type', models.CharField(blank=True, max_length=64, null=True)),
                ('object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
