# Generated by Django 5.2.1 on 2025-06-17 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0011_adminlogentry_sessionlog_delete_applogentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionlog',
            name='admin_user',
        ),
        migrations.DeleteModel(
            name='AdminLogEntry',
        ),
        migrations.DeleteModel(
            name='SessionLog',
        ),
    ]
