# Generated by Django 5.2.1 on 2025-06-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0012_remove_sessionlog_admin_user_delete_adminlogentry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletentry',
            name='card_type',
        ),
        migrations.AlterField(
            model_name='walletentry',
            name='wallet_type',
            field=models.CharField(choices=[('account', 'Account Number'), ('credit', 'Credit Card'), ('debit', 'Debit Card')], max_length=10),
        ),
    ]
