# Generated by Django 5.2.1 on 2025-06-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0013_remove_walletentry_card_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
